### ISSUE TITLE
0.0.11 : NOT Experimental. When choose Network Cable the Game Crashs

### ISSUE THREAD

**Issue by Loki1147** [CoderDE/FicsIt-Networks#101]
on non experimental version the game crashes. without special reason

edit: I tested it on Experimental and the same happend. So on both Versions its crashes by choosing the network cable

**Comment by Panakotta00** [comment]
It makes sense that it crashes in EA, but EX should not crash, and it does not for me...
are you 100% sure that you have 0.0.11 installed and EX? (check in the main menu the build ID of the game in the lower left corner and the version number in the mods section in the main menu)

**Comment by Loki1147** [comment]
Ja Ex works sorry forget to update to 0.0.11 on EX. so i have to sty on EA at 0.0.10?

**Comment by Panakotta00** [comment]
If you want to use FIN on EA? Yes
