### ISSUE TITLE
Crash to desktop

### ISSUE THREAD

**Issue by Zalbor** [CoderDE/FicsIt-Networks#118]
I'm currectly using the regular early release, not the experimental.
Whenever I start a computer, it will run my lua code just fine.
But eventually it will crash to the desktop.

When I have more then one computer running, it will crash to the desktop even faster.
When I start the game again from the last saving point, it will almost immediatly crash to the desktop.

When no computer is running, the game won't crash at all.

**Comment by Panakotta00** [comment]
It's likely that this will be fixed in the next update to major internal refactors... if the issue still persists after the update... plz reopen the issue...
and then also send the debug file you can generate by SMM
