### ISSUE TITLE
Crash using computer.beep()

### ISSUE THREAD

**Issue by pacas00** [CoderDE/FicsIt-Networks#12]
Attempting to use `computer.beep()` crashes satisfactory due to failed assertion, `Assertion failed: IsInGameThread()`.

Log attached.
[FactoryGame_Client_CrashOnly.log](https://github.com/CoderDE/FicsIt-Networks/files/4883270/FactoryGame_Client_CrashOnly.log)

Don't know how helpful this will be, but I know this snippet works to get things on the game thread.
`
AsyncTask(ENamedThreads::GameThread, [this]()
{
	//Stuff
});
`

**Comment by Panakotta00** [comment]
Thanks for the notice ^^
Should be fixed in the next update (very soon)
