### ISSUE TITLE
Many crashes and broken saves

### ISSUE THREAD

**Issue by M-Marvin** [CoderDE/FicsIt-Networks#120]
I had many game Crashed with the mod, but now one of my saves is broken.
By an autosave the game is crashed and the save is broken (crash wehen trying to load the world)
All older saves of the world are broken to.
All these world contains only 1 computer with folowing code.
The code is on a harddrive an called from the computer but I cant load the world to copy it.
The computer has been running for several days without problems.

Attached the code, it was not displayed correctly
[code.txt](https://github.com/CoderDE/FicsIt-Networks/files/5978045/code.txt)

The report is always the same:
`Version: 140083, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Epic, NetMode: Listen Server, IsUsingMods: Yes

Unhandled exception

FactoryGame_Win64_Shipping!FMallocBinned2::Realloc() [d:\ws\sb-201123102323-c9f\ue4\engine\source\runtime\core\public\hal\mallocbinned2.h:532]
FactoryGame_Win64_Shipping!FScriptArray::ResizeTo() [d:\ws\sb-201123102323-c9f\ue4\engine\source\runtime\core\public\containers\scriptarray.h:200]
FactoryGame_Win64_Shipping!UArrayProperty::DestroyValueInternal() [d:\ws\sb-201123102323-c9f\ue4\engine\source\runtime\coreuobject\private\uobject\propertyarray.cpp:540]
UE4_FicsItNetworks_Win64_Shipping
UE4_FicsItNetworks_Win64_Shipping
UE4_FicsItNetworks_Win64_Shipping
UE4_FicsItNetworks_Win64_Shipping
UE4_FicsItNetworks_Win64_Shipping
UE4_FicsItNetworks_Win64_Shipping
UE4_FicsItNetworks_Win64_Shipping
UE4_FicsItNetworks_Win64_Shipping
UE4_FicsItNetworks_Win64_Shipping
UE4_FicsItNetworks_Win64_Shipping
UE4_FicsItNetworks_Win64_Shipping
FactoryGame_Win64_Shipping!<lambda_83daf8ef5e8824f4bd940e5ce226921c>::operator()() [d:\ws\sb-201123102323-c9f\ue4\games\factorygame\source\factorygame\private\fgbuildablesubsystem.cpp:425]
FactoryGame_Win64_Shipping!FParallelForData::Process() [d:\ws\sb-201123102323-c9f\ue4\engine\source\runtime\core\public\async\parallelfor.h:134]
FactoryGame_Win64_Shipping!TGraphTask<FParallelForTask>::ExecuteTask() [d:\ws\sb-201123102323-c9f\ue4\engine\source\runtime\core\public\async\taskgraphinterfaces.h:842]
FactoryGame_Win64_Shipping!FTaskThreadAnyThread::ProcessTasksUntilQuit() [d:\ws\sb-201123102323-c9f\ue4\engine\source\runtime\core\private\async\taskgraph.cpp:853]
FactoryGame_Win64_Shipping!FTaskThreadBase::Run() [d:\ws\sb-201123102323-c9f\ue4\engine\source\runtime\core\private\async\taskgraph.cpp:524]
FactoryGame_Win64_Shipping!FRunnableThreadWin::Run() [d:\ws\sb-201123102323-c9f\ue4\engine\source\runtime\core\private\windows\windowsrunnablethread.cpp:96]`

**Comment by Panakotta00** [comment]
Can you plz send the debug file which you can generate within SMM?

**Comment by M-Marvin** [comment]
Where can I find the debug file?

**Comment by Panakotta00** [comment]
Open SMM, Debug -> Generate debug file

**Comment by M-Marvin** [comment]
[Uploading SMMDebug_2021-2-14_16-31-21.zip…]()

**Comment by M-Marvin** [comment]
The file has a size of 15MB
I can't uplad it

**Comment by M-Marvin** [comment]
It contains to 70% flowing line:
"[2021.02.14-16.01.43:205][740]LogPackageLocalizationCache: Warning: Skipping the cache update for the package asset groups due to a cache request from a non-game thread. Some localized packages may be missed for this query.2
And has 77780 lines

**Comment by Panakotta00** [comment]
You can get rid of those...

**Comment by M-Marvin** [comment]
I copied the last 400 lines:

[SMMDebug_2021-2-14_16-36-42.zip](https://github.com/CoderDE/FicsIt-Networks/files/5978078/SMMDebug_2021-2-14_16-36-42.zip)

**Comment by Panakotta00** [comment]
I hope I was able to fix it... but i can tell for sure since it was not reproduceable, if you have discord, you might want to join the server then I can send you quick fix

**Comment by M-Marvin** [comment]
I have discord, wait im joining the server.

**Comment by M-Marvin** [comment]
Is the crash/bug caused by my code or an bug in the mod?
I have crashes in other world too, but that is my first broken save and its the save with the lowest count of computers.

**Comment by Panakotta00** [comment]
The game should never crash, so no, not your fault

**Comment by M-Marvin** [comment]
I'm on the server, but it says that my account hasn't been claimed yet, if I click on claim, a login window comes out saying I'd already be registered.

**Comment by Panakotta00** [comment]
i think that relates to email verification... sounds like you havent verfied your email yet

**Comment by M-Marvin** [comment]
I didn't get an email and I used Discord before.

**Comment by M-Marvin** [comment]
Can you send me the instructions or can't it?

**Comment by Panakotta00** [comment]
https://discord.gg/3VfZ6Da that would be the invite... but jeah... the only thing i can imagine is that the email verification, that is like the only limitation i added

**Comment by M-Marvin** [comment]
Can you send it here?
Discord doesn't seem to work.

If not I'll look for it again tomorrow

**Comment by Panakotta00** [comment]
Nope... i cant... the file is too big...
you can also try to go to the official modding discord or SF discord and send me a DM

**Comment by M-Marvin** [comment]
Ok then I'll look again tomorrow, I want to do something on one of my projects today too.

**Comment by M-Marvin** [comment]
Oh one thing I forgot:
If I want to load the broken saves and delete the file with the code from the "Computers" folder beforehand, SF creates a new one but with an older code that has an error that always crashes the PC in the world.

**Comment by Panakotta00** [comment]
jeah thats to be expected since the game will make basically copy the stuff in such a drive folder into the save file... otherwise we could not handle multiple save files with the same drive but differnt drive content

**Comment by M-Marvin** [comment]
The old broken code is from about 1-2 days, I corrected it today, and 2 autosaves later I created this issue here because it crashed.

**Comment by M-Marvin** [comment]
Wehen i try to load the save into the "Satisfactory Calculator" map, it crashes als also

**Comment by M-Marvin** [comment]
Is there a way to delete this copy from the save? That seems to be the cause, or is this file you wanted to send me?

**Comment by Panakotta00** [comment]
jeah... i can't do much about that... i just simply have my stuff i serialize with a custom format, and it probably doesn't have a standard way of handling things...
there is somewere a save editor that is capable of doing such edits, with that you can try to delete the drive/floppy/computer
but as said... you should realy try to join the discord...
if the desktop app doesnt work, you can also try to use the discord web app

**Comment by M-Marvin** [comment]
Im trying the web app, tomorrow i downolad the desktop app an try it again.

**Comment by M-Marvin** [comment]
Other servers work fine, only the ficsit-networks server has this problem

**Comment by Panakotta00** [comment]
odd... you can as said... also try to simply send me a dm Panakotta00#1001

**Comment by M-Marvin** [comment]
![image](https://user-images.githubusercontent.com/69386758/107884448-7beb6780-6ef5-11eb-8143-d7a78ecf241c.png)
...

**Comment by M-Marvin** [comment]
Ok, I'll continue with it tomorrow ...

**Comment by Panakotta00** [comment]
It would be realy cool to get it fixed as soon as possible cuz i dont want to have 3 releases on 3 following days... because there is also another crash bug that seems to be more common i want to release the fix for

**Comment by M-Marvin** [comment]
As I said, the first time a crash has damaged a save, and also all previous autosaves (they were just not "active").
I make mods for Minecraft, and I often have something like that, but I've never had that it affects several game stands.

**Comment by Panakotta00** [comment]
its unlikely that
1. your save is damaged... it should be back to normal when you just uninstall the mod... otherwise UE like crashed while saving to file, which should not be the case... because serialization would be the big problem but that happens befor it finally gets saved to file
2. i think its just that, the problem causing game state persisted for longer while you have been playing the game, and the game created autosaves already... you then notices just as you loaded a save

**Comment by RozeDoyanawa** [comment]
The latter happened to me yesterday

**Comment by M-Marvin** [comment]
The game is crashed by making the autosave "Welt_3_autosave_2".
But I have tried to load all Autosaves from 0-2 and all are broken.
I have used the older saves bevore, and bevore the game crash it has worked.

Ab yes, when i uninstall the mod, the save is working, but all the first big factory in the world is automated with a computer.
I cant uninstall the mod, wehen i will play with this save.
