### ISSUE TITLE
Crashing client in multiplayer game

### ISSUE THREAD

**Issue by jdiazcano** [CoderDE/FicsIt-Networks#121]
The game crashes on startup of the client or whenever I place and start the computer but it works if playing alone. I have no clue what could be wrong

The current code is:

```lua
screen = component.proxy(component.findComponent("Screen")[1])

gpu = computer.getGPUs()[1]
 
gpu:bindScreen(screen)
gpu:setBackground(0, 0, 0, 0)
gpu:setSize(100, 400)
w,h = gpu:getSize()
gpu:fill(0,0,w,h," ")
gpu:flush()

dispensers = component.findComponent("Dispenser")
print(dispensers)

function numOf(inventory)
  local number = 0
  local itemName = "Unknown"
  for i=0,inventory.size,1 do
    local stack = inventory:getStack(i)
    if (stack ~= nil and stack.item ~= nil and stack.item.type ~= nil and itemName == "Unknown") then
      itemName = stack.item.type.name
    end

    if (stack ~= nil) then
      number = number + stack.count
    end
  end
  return itemName, number
end

while true do
  event.pull(0.25)
  gpu:fill(0,0,w,h," ")

  local index = 1
  for _, dispenser in pairs(dispensers) do
    local proxyDispenser = component.proxy(dispenser)
    local itemName, number = numOf(proxyDispenser:getInventories()[1])
    gpu:setText(0, 25 + index, itemName .. ": " .. number)
    index = index - 1
  end

  gpu:flush()
end
```

[debug-logs.zip](https://github.com/CoderDE/FicsIt-Networks/files/6011306/debug-logs.zip)

**Comment by Bommik** [comment]
what leads to the crash is the screen resolution. I had the same bug with another player. the maximum resolution that is possible without game crashing is 149x49.

**Comment by jdiazcano** [comment]
Yup, that was the issue

**Comment by TheGreyDiamond** [comment]
So technically this issue is done and can be closed?

**Comment by jdiazcano** [comment]
There is still a crash if you write more than 149x49 (haven't tried lately though)

**Comment by neyrou** [comment]
Same issue for me. One other thing noticeable : the player which host the game did not crash, only the the 2 others players (including me) had a game crash.
I don't have the exact screen resolution, but it was bigger than the other screen added before.

An other point : only the host can see modified network ID. The left item list is always empty for other players. But this need probably an other github issue ticket.

**Comment by gogelDE** [comment]
> 
> 
> Same issue for me. One other thing noticeable : the player which host the game did not crash (and which has done the run action on the computer), only the the 2 others players (including me) had a game crash.
> I don't have the exact screen resolution, but it was bigger than the other screen added before.
> 
> An other point : only the host can see modified network ID. The left item list is always empty for other players. But this need probably an other github issue ticket.

Same problem here

**Comment by Panakotta00** [comment]
It will likely get fixed with the next update...
tho... the "refresh-rate" might not be the best
