### ISSUE TITLE
Crash on load from save

### ISSUE THREAD

**Issue by Alymsin** [CoderDE/FicsIt-Networks#123]
When trying to load up the game from a save, I'm getting an unhandled exception error.

Crash log uploaded.

Save game uploaded.

Game will load when deselecting the Ficsit Networks mod from the SMM

[Moddy_autosave_0.zip](https://github.com/CoderDE/FicsIt-Networks/files/6058518/Moddy_autosave_0.zip)

[UE4CC-Windows-2D9CD3B0488396DB5F559290DF1BDC61_0000.zip](https://github.com/CoderDE/FicsIt-Networks/files/6058513/UE4CC-Windows-2D9CD3B0488396DB5F559290DF1BDC61_0000.zip)

**Comment by Panakotta00** [comment]
That log doesn't realy tell me anything... but eitherway with the next update I push some refactoring to the FicsIt-Kernel and it's serialization system... whichs is the main trouble maker in save loading...
so we should hope it then just works...
feel free to reopen the issue if the crash still persists.
