### ISSUE TITLE
Multiplayer CPU issues

### ISSUE THREAD

**Issue by Popax21** [CoderDE/FicsIt-Networks#125]
When playing with multiple players, for all players except the host the computer UI says "No CPU found". This issue wasn't present in 0.0.1, I suspect it has something to do with commit 402b93346a7e066d8aca84433500034ef07d0d02 or 74e6cea87cda71ef1f629fa1c8088a82bea04bd1, because that are the only CPU related commits in this timespan.

**Comment by Panakotta00** [comment]
Should be fixed with c3710198d9e536ec389a57704d58ae67ae3f2cb1
