### ISSUE TITLE
Codable splitters don't seem to work?

### ISSUE THREAD

**Issue by arigo** [CoderDE/FicsIt-Networks#126]
It might be just me, but codable splitters don't seem to work at all right now:

``` lua
splitter1 = component.proxy("E3DC3FCB418657200524E9904166C836")

while true do
  event.pull(0.1)
  if splitter1:getInput() then
    print(splitter1:transferItem(1))
  end
end
```

This keeps printing `false` and the items waiting in the input are sitting there.  For reference, the same piece of code works fine with codable mergers (with `getInput(1)` of course).

**Comment by arigo** [comment]
Never mind, it works after I delete and re-create the input conveyor belt.  Maybe it was badly attached.  I realize now that `if splitter1:getInput() then` is bogus, as such a check always passes (even though it's been presented like this in various youtube videos).  Maybe you could add a basic example to the documentation showing the right way, which appears to be:

``` lua
splitter1 = component.proxy("E3DC3FCB418657200524E9904166C836")

while true do
  event.pull(0.1)
  if splitter1:getInput().Type then
    print(splitter1:transferItem(1))    -- prints false if the output 1 is full
  end
end
```

**Comment by arigo** [comment]
FWIW, https://docs.ficsit.app/ficsit-networks/0.0.1/lua/examples/storageRefill.html also uses the line `if splitter:getInput() then`, which I now think is bogus as such a check always passes.

**Comment by Panakotta00** [comment]
I hope the issue you were having will be fixed with the next update...
