### ISSUE TITLE
Duplicate "milestones" in the Hub Terminal

### ISSUE THREAD

**Issue by BoredLuddite** [CoderDE/FicsIt-Networks#13]
Hi, 

Awesome mod !!!

Noticed that after unlocking Basic Networking the additional milestones (Flow Control...Computer Graphics) are duplicated 3 times on Tier 3.

Thanks

**Comment by BoredLuddite** [comment]
Hi,

Used the Satisfactory Save Editor to remove the duplicates - all good but I assume it would happen again when unlocking Basic Networking at the Hub in a different save?

Thanks

**Comment by Panakotta00** [comment]
It looks to me like a problem with the custom ADA message from the Basic Networks Hub unlock.
I made a quick fix by simply removing that and I hope it works after that.

I would be glad if you explain it further what you did to get those duplicates so I can find a better solution where we can keep the custom ADA message. ^^

**Comment by BoredLuddite** [comment]
Hi Panokotta00,

Nothing special I just unlocked Basic Networks - and yes I'd like to see the custom ADA message remain :-)
