### ISSUE TITLE
getModules() crash

### ISSUE THREAD

**Issue by pritchard6782** [CoderDE/FicsIt-Networks#130]
The following code crashes the game

`constructors = component.proxy(component.findComponent("Constructor"))
panels = component.proxy(component.findComponent("Panel"))

clock = 2.1
standby = false

for _, panel in pairs(panels) do
  for _, m in pairs(panel:getModules()) do
    print(m)
  end
end
`

Version: 140083, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Steam, NetMode: Listen Server, IsUsingMods: Yes

Unhandled exception

FactoryGame_Win64_Shipping!FMallocBinned2::Realloc() [d:\ws\sb-201123102323-c9f\ue4\engine\source\runtime\core\public\hal\mallocbinned2.h:532]
FactoryGame_Win64_Shipping!FScriptArray::ResizeTo() [d:\ws\sb-201123102323-c9f\ue4\engine\source\runtime\core\public\containers\scriptarray.h:200]
FactoryGame_Win64_Shipping!UArrayProperty::DestroyValueInternal() [d:\ws\sb-201123102323-c9f\ue4\engine\source\runtime\coreuobject\private\uobject\propertyarray.cpp:540]
UE4_FicsItNetworks_Win64_Shipping!UFINUFunction::Execute() [g:\projects\satisfactory\mods\ficsit-networks\source\ficsitnetworks\reflection\finufunction.h:57]
UE4_FicsItNetworks_Win64_Shipping!FicsItKernel::Lua::luaCallFINFunc() [g:\projects\satisfactory\mods\ficsit-networks\source\ficsitnetworks\ficsitkernel\processor\lua\luaref.cpp:46]
UE4_FicsItNetworks_Win64_Shipping!FicsItKernel::Lua::luaInstanceFuncCall() [g:\projects\satisfactory\mods\ficsit-networks\source\ficsitnetworks\ficsitkernel\processor\lua\luainstance.cpp:122]
UE4_FicsItNetworks_Win64_Shipping!luaD_precall()
UE4_FicsItNetworks_Win64_Shipping!luaV_execute()
UE4_FicsItNetworks_Win64_Shipping!luaD_callnoyield()
UE4_FicsItNetworks_Win64_Shipping!luaD_rawrunprotected()
UE4_FicsItNetworks_Win64_Shipping!lua_resume()
UE4_FicsItNetworks_Win64_Shipping!FicsItKernel::Lua::LuaProcessor::luaTick() [g:\projects\satisfactory\mods\ficsit-networks\source\ficsitnetworks\ficsitkernel\processor\lua\luaprocessor.cpp:350]
UE4_FicsItNetworks_Win64_Shipping!FicsItKernel::Lua::LuaProcessorTick::syncTick() [g:\projects\satisfactory\mods\ficsit-networks\source\ficsitnetworks\ficsitkernel\processor\lua\luaprocessor.cpp:160]
UE4_FicsItNetworks_Win64_Shipping!AFINComputerCase::Factory_Tick() [g:\projects\satisfactory\mods\ficsit-networks\source\ficsitnetworks\computer\fincomputercase.cpp:156]
FactoryGame_Win64_Shipping!<lambda_83daf8ef5e8824f4bd940e5ce226921c>::operator()() [d:\ws\sb-201123102323-c9f\ue4\games\factorygame\source\factorygame\private\fgbuildablesubsystem.cpp:425]
FactoryGame_Win64_Shipping!FParallelForData::Process() [d:\ws\sb-201123102323-c9f\ue4\engine\source\runtime\core\public\async\parallelfor.h:134]
FactoryGame_Win64_Shipping!TGraphTask<FParallelForTask>::ExecuteTask() [d:\ws\sb-201123102323-c9f\ue4\engine\source\runtime\core\public\async\taskgraphinterfaces.h:842]
FactoryGame_Win64_Shipping!FTaskThreadAnyThread::ProcessTasksUntilQuit() [d:\ws\sb-201123102323-c9f\ue4\engine\source\runtime\core\private\async\taskgraph.cpp:853]
FactoryGame_Win64_Shipping!FTaskThreadBase::Run() [d:\ws\sb-201123102323-c9f\ue4\engine\source\runtime\core\private\async\taskgraph.cpp:524]
FactoryGame_Win64_Shipping!FRunnableThreadWin::Run() [d:\ws\sb-201123102323-c9f\ue4\engine\source\runtime\core\private\windows\windowsrunnablethread.cpp:96]

**Comment by Panakotta00** [comment]
Should be fixed with the next version,

if the issue still persists, feel free to reopen or create a new issue ^^

Thanks for your support :3
