### ISSUE TITLE
Game crashed on boot

### ISSUE THREAD

**Issue by EnhancedC** [CoderDE/FicsIt-Networks#135]
before this i was messing with running code from a file using filesystem.loadFile and filesystem.doFile
sometimes when i saved the file it would crash my game
witch gave me this 

Fatal error!

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x00000000

0x00007ffaad42b43c FactoryGame-Renderer-Win64-Shipping.dll!<lambda_e16e73cbb2a4ec8b8a339f4827af07ce>::operator()() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\renderer\private\scenevisibility.cpp:529]
0x00007ffaad4487f3 FactoryGame-Renderer-Win64-Shipping.dll!ParallelForImpl::TParallelForData<TFunctionRef<void __cdecl(int)> >::Process() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\core\public\async\parallelfor.h:169]
0x00007ffaad43c2cd FactoryGame-Renderer-Win64-Shipping.dll!TGraphTask<ParallelForImpl::TParallelForTask<TFunctionRef<void __cdecl(int)> > >::ExecuteTask() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\core\public\async\taskgraphinterfaces.h:849]
0x00007ffaadd5a93a FactoryGame-Core-Win64-Shipping.dll!FTaskThreadAnyThread::ProcessTasksUntilQuit() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\core\private\async\taskgraph.cpp:862]
0x00007ffaadd5e3c2 FactoryGame-Core-Win64-Shipping.dll!FTaskThreadBase::Run() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\core\private\async\taskgraph.cpp:529]
0x00007ffaadf5cddb FactoryGame-Core-Win64-Shipping.dll!FRunnableThreadWin::Run() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\core\private\windows\windowsrunnablethread.cpp:86]
0x00007ffaadf557f1 FactoryGame-Core-Win64-Shipping.dll!FRunnableThreadWin::GuardedRun() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\core\private\windows\windowsrunnablethread.cpp:35]
0x00007ffbaf8c7034 KERNEL32.DLL!UnknownFunction []
0x00007ffbb0b62651 ntdll.dll!UnknownFunction []

Crash in runnable thread TaskGraphThreadHP 18

now when i try and load my save game it just crashes 
it crashed on both experimental and release versions

Fatal error!

Unhandled Exception: 0xe06d7363

0x00007ffbae714b89 KERNELBASE.dll!UnknownFunction []
0x00007ffb932d6480 VCRUNTIME140.dll!UnknownFunction []
0x00007ffa9dec74b8 FactoryGame-FicsItNetworks-Win64-Shipping.dll!std::filesystem::_Throw_system_error_from_std_win_error() [C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\INCLUDE\filesystem:50]
0x00007ffa9dcd891f FactoryGame-FicsItNetworks-Win64-Shipping.dll!std::filesystem::_Convert_wide_to_narrow<std::char_traits<char>,std::allocator<char> >() [C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\INCLUDE\filesystem:91]
0x00007ffa9dcecbba FactoryGame-FicsItNetworks-Win64-Shipping.dll!CodersFileSystem::Path::Path() [G:\Projects\Satisfactory\SatisfactoryModLoader\Plugins\FicsItNetworks\Source\FicsItNetworks\FicsItKernel\FicsItFS\Library\Path.cpp:8]
0x00007ffa9def5881 FactoryGame-FicsItNetworks-Win64-Shipping.dll!CodersFileSystem::WindowsFileWatcher::tick() [G:\Projects\Satisfactory\SatisfactoryModLoader\Plugins\FicsItNetworks\Source\FicsItNetworks\FicsItKernel\FicsItFS\Library\WindowsFileWatcher.cpp:47]
0x00007ffa9def632b FactoryGame-FicsItNetworks-Win64-Shipping.dll!FFINKernelFSDevDevice::tickListeners() [G:\Projects\Satisfactory\SatisfactoryModLoader\Plugins\FicsItNetworks\Source\FicsItNetworks\FicsItKernel\FicsItFS\DevDevice.cpp:74]
0x00007ffa9debff8b FactoryGame-FicsItNetworks-Win64-Shipping.dll!UFINKernelSystem::Tick() [G:\Projects\Satisfactory\SatisfactoryModLoader\Plugins\FicsItNetworks\Source\FicsItNetworks\FicsItKernel\FicsItKernel.cpp:139]
0x00007ffa9de41177 FactoryGame-FicsItNetworks-Win64-Shipping.dll!AFINComputerCase::Factory_Tick() [G:\Projects\Satisfactory\SatisfactoryModLoader\Plugins\FicsItNetworks\Source\FicsItNetworks\Computer\FINComputerCase.cpp:134]
0x00007ffa9ec23fe4 FactoryGame-FactoryGame-Win64-Shipping.dll!<lambda_643bc97631e1119ca6d24cb4ba21c30f>::operator()() [d:\ws\sb-210421141322-21c\ue4\games\factorygame\source\factorygame\private\fgbuildablesubsystem.cpp:478]
0x00007ffa9ec04183 FactoryGame-FactoryGame-Win64-Shipping.dll!ParallelForImpl::TParallelForData<TFunctionRef<void __cdecl(int)> >::Process() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\core\public\async\parallelfor.h:169]
0x00007ffa9ebefe7d FactoryGame-FactoryGame-Win64-Shipping.dll!TGraphTask<ParallelForImpl::TParallelForTask<TFunctionRef<void __cdecl(int)> > >::ExecuteTask() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\core\public\async\taskgraphinterfaces.h:849]
0x00007ffab3b0a93a FactoryGame-Core-Win64-Shipping.dll!FTaskThreadAnyThread::ProcessTasksUntilQuit() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\core\private\async\taskgraph.cpp:862]
0x00007ffab3b0e3c2 FactoryGame-Core-Win64-Shipping.dll!FTaskThreadBase::Run() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\core\private\async\taskgraph.cpp:529]
0x00007ffab3d0cddb FactoryGame-Core-Win64-Shipping.dll!FRunnableThreadWin::Run() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\core\private\windows\windowsrunnablethread.cpp:86]
0x00007ffab3d057f1 FactoryGame-Core-Win64-Shipping.dll!FRunnableThreadWin::GuardedRun() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\core\private\windows\windowsrunnablethread.cpp:35]
0x00007ffbaf8c7034 KERNEL32.DLL!UnknownFunction []
0x00007ffbb0b62651 ntdll.dll!UnknownFunction []

Crash in runnable thread TaskGraphThreadHP 17

**Comment by Panakotta00** [comment]
letely I fixed a couple of issues with the file system... this looks like one of the bugs... try to use the in-dev version... feel free to re open if the issue still persists
