### ISSUE TITLE
Crash on "Lua Processor Persist" sometimes

### ISSUE THREAD

**Issue by Witherking25** [CoderDE/FicsIt-Networks#138]
[UE4CC-Windows-165CD1154DA1E28BBA59B1A50B993448_0001.zip](https://github.com/CoderDE/FicsIt-Networks/files/6696551/UE4CC-Windows-165CD1154DA1E28BBA59B1A50B993448_0001.zip)

**Comment by Panakotta00** [comment]
Have you encountered the issue with the normal released version on SMR/SMM
or do you use the in-dev version?

**Comment by Witherking25** [comment]
I’m just using the latest version in the mod manager thingy

**Comment by Panakotta00** [comment]
ah ok...
with the upcoming version i made some deeper changes (even like updating from Lua 5.3 to 5.4)
so it might be fixed then...

if the issue persists even after the upcoming update, feel free to reopen or create a new issue ^^
thx for your help :3
