### ISSUE TITLE
ModuleTextDiscplay.text crashes

### ISSUE THREAD

**Issue by Altaric** [CoderDE/FicsIt-Networks#139]
Setting the text property crashes to desk.
Can provide the save to reproduce the crash if needed.

Code is trivial:
board = component.proxy(component.findComponent("Keybd"))[1]
modules = board.getModules(board)
panels = {}
for n, m in pairs(modules) do
  if m:getType().name == "ModuleTextDisplay_C" then table.insert(panels, m) end
end
assert(#panels > 0)
print(panels[1].internalName)
panels[1].text = "test"

**Comment by Panakotta00** [comment]
Have you used the version uploaded to SMR
or the in-dev version?

**Comment by Panakotta00** [comment]
either way it should be fixed with next update...

feel free to reopen or create a new issue if the problem persist ^^

thanks for your support :3
