### ISSUE TITLE
getFluidContent, getFlowDrain and getFlowFill no longer update when player moves away from tank.

### ISSUE THREAD

**Issue by your-mate** [CoderDE/FicsIt-Networks#18]
I have a display that shows tank capacity and flow rates. It works fine for the tanks that I can see from the computer, but as the distance from the player to the tanks increase eventually the values no longer get updated. Only way I have found to get updated values is to move the player closer to the tanks.

**Comment by Panakotta00** [comment]
Should be fixed in the next update ^^
