### ISSUE TITLE
Multiplayer not work

### ISSUE THREAD

**Issue by sveini4u** [CoderDE/FicsIt-Networks#22]
game crash when you join multiplayer!

I hope you can fix it :) that have been nice! :D

Thanks for this nice mod!

**Comment by Panakotta00** [comment]
Multiplayer is not supported yet.
It will get worked on soon.

**Comment by UplinkCoder** [comment]
I would be happy to help work on this, can you give me some pointers to the places of the source-code which are relevant?

**Comment by Panakotta00** [comment]
Not realy... and I would kot reccomend to...
there are some changes coming up to the Lua environment (probably) which might cause problems if MP is done now... and MP is basically the next thing i work on xD

**Comment by UplinkCoder** [comment]
@Panakotta00 I see, thanks for your quick reply!

**Comment by Panakotta00** [comment]
Multiplayer is supported now since version 0.0.8 ^^

**Comment by UplinkCoder** [comment]
Awesome! Thanks @Panakotta00
