### ISSUE TITLE
network manager gui

### ISSUE THREAD

**Issue by endervw** [CoderDE/FicsIt-Networks#23]
when i use the network manager on a component and try close the gui, the escape button doesn't work and when i press the close on the gui, the gui itself closes but its like its still open as the cursor remains active as well as the  test entry field (also invisible) and i cant seem to close it and so i have to restart the game to get out of that.

**Comment by Panakotta00** [comment]
This issue gets resolved with commit https://github.com/CoderDE/FicsIt-Networks/commit/d47ff4465789d50125fcdd2108517adee1d0ba75 and will be released in the next update.
