### ISSUE TITLE
Unable to access id and nick properties

### ISSUE THREAD

**Issue by ah42** [CoderDE/FicsIt-Networks#31]
Following along with the example video https://www.youtube.com/watch?v=iCQAO7VWu-g, attempting to access the id and nick properties results in the error "EEPROM:3: Instance is not a network component"
As poles are no longer components, I have tried this with storage containers, constructors, and the computer. They all return the same error.

com = component.proxy("DE2B41954B4B01A6F87F43B68EB6C404")
print(com.nick)

**Comment by Panakotta00** [comment]
should be fixed with the latest version
