### ISSUE TITLE
multiple copies of recepies in HUB

### ISSUE THREAD

**Issue by tapetar26** [CoderDE/FicsIt-Networks#38]
I am looking forward to use this mod, looks amazing.
This is low priority bug, things are working, but look weird. I am not even sure, if it can be reproduced on another computer.

I was about to unlock the stuff for the mod, when I found out that I there is multiple recepies in HUB unlock menu. Basic network and Network wall plugs are fine, but everything else is there 32x. They are copies of each other, when one is unlocked, all 32 get unlocked.

![image](https://user-images.githubusercontent.com/69325795/89582155-6f949c80-d838-11ea-803c-9c3cbb8a5175.png)
![image](https://user-images.githubusercontent.com/69325795/89584299-221a2e80-d83c-11ea-8949-d6482d0d5a99.png)

I have save file for for purposes of debuging.

I play on Experimental
run W10 1909 64bit
starting game through SMM, to be up to date.

[debug.zip](https://github.com/CoderDE/FicsIt-Networks/files/5038069/debug.zip)

**Comment by Panakotta00** [comment]
This is a general problem with modding and can happen to any mod... there is no known cure for it right now.

**Comment by tapetar26** [comment]
I Didn't know that. Thank you for your answer.
