### ISSUE TITLE
Network Wall Plug and Double Network Wall Plug are unlocked as a milestone in the HUB, rather than as a purchase in the AWESOME Shop like all the other wall plugs.

### ISSUE THREAD

**Issue by Esper89** [CoderDE/FicsIt-Networks#39]

**Comment by Sinuswutz** [comment]
Modding the content of the Awesome Shop doesn't seem to work yet. I've watched Panakotta00 try doing it on a live-stream for about two hours before deciding to just give us the wall-plugs through a milestone instead.

**Comment by Panakotta00** [comment]
Should be implemented now with version 0.0.9
