### ISSUE TITLE
Where are the lua code located?

### ISSUE THREAD

**Issue by ProgCat-op** [CoderDE/FicsIt-Networks#40]
Hello devs, I recently writing an OS with the FIN mod.
I would like to write code outside the game (editor), and I can't find where the script located in my computer.

It will be nice to know the path of the data stored :)

**Comment by RozeDoyanawa** [comment]
The scripts you write ingame is only stored in the save file itself.
There is bootloaders that use filesystem to load external code. Perhaps something for you

**Comment by Panakotta00** [comment]
You can learn more in the [docs](https://docs.ficsit.app/ficsit-networks/0.0.1/lua/api/FileSystem.html).
