### ISSUE TITLE
Game crash when dealing with ItemType:getMembers()

### ISSUE THREAD

**Issue by Justintime505** [CoderDE/FicsIt-Networks#47]
Doing a bit of fiddling and ran into a reproducible game crash. The variable mergerFromConstructor is a merger that is being fed screws. Find the code below:

```
co = component.findComponent("Constructor")
constructors = component.proxy(co)
mergerFromConstructors = component.proxy(component.findComponent("Merger fromConstructors")[1])
requestedType = "Screw"
requestedQty = 100

tempItem = mergerFromConstructors:getInput(2)

for _,n in pairs(tempItem) do
   print(n)
   temp = n
end

for _,n in pairs(temp:getMembers()) do
   print(n)
end
```

Log File:

[FactoryGame-backup-2020.08.19-01.44.55.log](https://github.com/CoderDE/FicsIt-Networks/files/5093622/FactoryGame-backup-2020.08.19-01.44.55.log)

**Comment by SebastianHD** [comment]
Same issue when doing recipe:getMembers(), where recipe is from machine:getRecipe().

**Comment by Justintime505** [comment]
> Same issue when doing recipe:getMembers(), where recipe is from machine:getRecipe().

I also just ran into that one as well.
