### ISSUE TITLE
Networking Milestones repeat in Tier 3 after unlocking Basic Networks

### ISSUE THREAD

**Issue by thor79** [CoderDE/FicsIt-Networks#49]
I just got done unlocking basic networks. After doing so, I went to see what else there was to unlock in Tier 3. I noticed that the milestones for networking start repeating after what should be the final milestone in my tier 3 list. This was not how it was before I unlocked Basic Networking. In the screenshots the final milestone in my tier 3 list should be carbon refining.
![image](https://user-images.githubusercontent.com/299155/90986557-dcef3f80-e551-11ea-9b7a-6b0d781d76ec.png)
![image](https://user-images.githubusercontent.com/299155/90986569-f7291d80-e551-11ea-962b-7bde2487d8a2.png)
![image](https://user-images.githubusercontent.com/299155/90986583-060fd000-e552-11ea-8020-48433e45921b.png)

**Comment by Panakotta00** [comment]
That's a known issue for SF modding in general and doesn't really apply to just this mod ^^
