### ISSUE TITLE
A place to store user generated component-specific data

### ISSUE THREAD

**Issue by jmarshallpresnell** [CoderDE/FicsIt-Networks#50]
Suggest having a three or four empty strings in the base component that can be read/written by code to store user-defined component-specific information. These may be used for any purpose by the program for storing state or operational values that can be operated on in a pseudo-class-specific manner (reducing code complexity in maintaining arbitrary states everywhere), etc.

As a simple example, something as simple as the code emitting a specific number of items from a splitter on command could then be easily generalized in the code, and altered in quantity and output belt by the splitter's user-defined data.

**Comment by Archengius** [comment]
Why not just use weak key tables?

**Comment by Panakotta00** [comment]
As Arch said, you can just make some stuff your self within the scripts... like a computer as central settings manager or so...
And you can also use the nick field as data storage... One of the [Docs Examples](https://docs.ficsit.app/ficsit-networks/0.0.1/lua/examples/storageRefill.html) even uses it.
