### ISSUE TITLE
[ Low Importance ] Tier 3 Icons Repeating Early Access CL#125236

### ISSUE THREAD

**Issue by UKLoneWolf** [CoderDE/FicsIt-Networks#53]
![2020 08 28-20 13](https://user-images.githubusercontent.com/8024927/91606944-fe459680-e96a-11ea-81d7-7fbe058a3c66.png)

Icons repeat on Tier 3 only the below are repeating and can be selected.

Flow Control - I/O&Control - Modular I/O - Digital Storage - Computer Graphics

**Comment by trunkyredstone** [comment]
This is an issue that can happen with every mod + modded milestone, and unfortunately there is no fix.

**Comment by UKLoneWolf** [comment]
ok, thanks for the reply.
