### ISSUE TITLE
Compatibility note: Permaday mod / computer.time() function

### ISSUE THREAD

**Issue by jmarshallpresnell** [CoderDE/FicsIt-Networks#57]
If one uses the Permaday mod to set the game time of day to a specific time, the computer.time() function will return a value that never changes.

This is not the case with computer.millis(), so it may be able to be used as a workaround in some cases.

Suggest noting this in the docs for computer.time()

**Comment by Panakotta00** [comment]
I think this is unnecessary since the docs are meant for the default behavior of everything. And if a mod changes it, then it's obvious that it also changes the affected FIN stuff.
Otherwise, I would need to add notices for every other mod there is and which changes some behavior...
