### ISSUE TITLE
[Issue] Modular regular button can't be pressed by user in multiplayer

### ISSUE THREAD

**Issue by TheGreyDiamond** [CoderDE/FicsIt-Networks#64]
I joined a friends Satisfactory session. We have a button placed onto a Modular Control Panel, with a script we constantly change to buttons colour, the host can see the changes, the joined player doesn't. The joined player is also unable to press the button. Changing the network quality to "Ultra", like recommended on the discord, didn't fix it. 

**Steps to reproduce:**
1. Open a world and place a modular control panel and a button
2. Write code to change the colour of the button
3. Make a seconds player join the session and observe

**Comment by TheGreyDiamond** [comment]
Kinda fixed in last update, colour changing works now. Pressing not. Please reopen! @Panakotta00

**Comment by Panakotta00** [comment]
Can you check now (till the press by client reaches the server can take up to a couple of seconds depending on network quality, settings and world size/complexity)

**Comment by TheGreyDiamond** [comment]
I will try to check soon.

**Comment by Panakotta00** [comment]
Should hopefully be fixed in the latest update, plz check and reopen the issue if the problem still persists.
