### ISSUE TITLE
Codeable splitter stops working

### ISSUE THREAD

**Issue by SebastianHD** [CoderDE/FicsIt-Networks#68]
The codeable splitters stop working on world load. The Lua code doesn't crash, but nothing comes out of the splitters any more. Oddly, the ones on my first network work just fine.

splitter:canOutput returns true on all slots.
splitter:transferItem returns false on all slots.
standby is false. Switching it to true and back to false doesn't help.
splitter:getInventories()[1].itemCount is 0
also tried flush just in case

Technically, two items will get output. It seems like the input queue doesn't get refilled. I can in fact delete and recreate the input belt and then it will work again.

It's possible the splitters on my first network were created before the last mod update, so maybe that is why they behave differently.

**Comment by RozeDoyanawa** [comment]
I have encontered this too. Had to rebuild the codable splitter. Its a random issue. Or its an issue where an item is in the splitter upon save. Sorry, cant give any more details, was a while ago since I encountered it.

**Comment by SebastianHD** [comment]
I did some more testing. It looks like once the input belt is deleted and created again, it will work after that on all future saves. In fact, if I don't connect the input, do a save and reload that save, then connect the input for the first time, it works fine for all future saves. As far as I can tell, it doesn't have to do with the buffer being occupied or not during save, it still happened when the input was connected for first time.

**Comment by Panakotta00** [comment]
It should be fixed with the latest version, if not, just reopen the issue ^^
