### ISSUE TITLE
0.0.10 Game Freezing issue

### ISSUE THREAD

**Issue by LuucEarth** [CoderDE/FicsIt-Networks#78]
Im pretty sure this has something to do with out of memory errors not being handled correctly or something.

in 0.0.8 this same code throws an OOM error and allows me to restart the computer. 
Newer versions the computer stops with no error report and trying to restart it causes the game to freeze completely.

in 0.0.9  I was able to try and dismantle the computer and it caused a game crash with the info attached. 
in 0.0.10 even trying to dismantle the computer, or even just trying to manually create a save point caused the game to freeze and required a complete restart of my computer to fix.  
[SMMDebug_2020-8-24_1-26-37.zip](https://github.com/CoderDE/FicsIt-Networks/files/5279901/SMMDebug_2020-8-24_1-26-37.zip)

**Comment by Panakotta00** [comment]
It would be nice if you could enable the SML debug-mode, recause the freeze (in 0.0.10)...
It would be also nice if you could try to find the smallest code snippet possible that causes the issue and send it.

**Comment by Panakotta00** [comment]
The next Update will contain huge refactors espetially in the program scope were this issue appears to be...

it would be cool if you could check that after the next update and open a new issue ticket if the problem still occurs.
