### ISSUE TITLE
Something wrong with inventories on Factories

### ISSUE THREAD

**Issue by mastermannrw** [CoderDE/FicsIt-Networks#86]
Hey.
I try to get a graphical overview for a Factory. To have the right item names displayed i get the inventories and get the name from the item in the stack.
I ran in the following problem:

for a,b in pairs(fab:getInventories()) do
 print(a,b)
 for c,d in pairs(b:getStack(1)) do
  print(c,d)
 end
end

I got three inventories. So far so good. Inventory one has an item as a table in. But should not have also 2 and three an item in?
Its the same with getInputInv and getOutputInv. One works as aspected the other dont.

kind regards.

**Comment by Panakotta00** [comment]
Depends on what your inventories contain... and stack index starts with 0 and not 1 ^^

**Comment by mastermannrw** [comment]
Okay. Lets take a manufactor. Has three inventories. Right?
Each inventorie has exactly one stack. Also Right?
on inventory one i got the stack. But not on two and three. Also i change the stackindex to 0. Nothing changed.

**Comment by mastermannrw** [comment]
And:
fab:getInputInv():getStack(1).item["type"] -> Works
fab:getOutputInv():getStack(1).item["type"] -> Works not
Should not both so the same except the return parameter?

**Comment by Bommik** [comment]
> 
> 
> Okay. Lets take a manufactor. Has three inventories. Right?
> Each inventorie has exactly one stack. Also Right?
> on inventory one i got the stack. But not on two and three. Also i change the stackindex to 0. Nothing changed.

Yes there are 3 inventories in a manufacturer. 
1. Inventory  - Input (4 slots) 
2. Inventory - Output (1 slot) 
3. Inventory - Power Shard (3 slots)

and if the slot is empty you won't get any item from this slot.
>
>
> And:
> fab:getInputInv():getStack(1).item["type"] -> Works
> fab:getOutputInv():getStack(1).item["type"] -> Works not
> Should not both do the same except the return parameter?

No, that shouldn't return the same thing. Your output inventory has only one slot. To expect something on the second slot makes no sense^^. As Panakotta00 said the index starts with 0 so the first slot has the index 0.

In my opinion there is currently no issue

**Comment by mastermannrw** [comment]
Okay, I will try it out tomorrow.
Thanks for the reply. Maybe could be i thought first inventory input slot one, second one input slot two and the third one is the output slot.

**Comment by Panakotta00** [comment]
As said... try to use index 0... not 1

**Comment by mastermannrw** [comment]
Following Code where fab is a manufactor also two input slots producing frames.
print(fab:getInventories()[1]:getStack(0).item["type"]) - expected reinforced plate ->got: reinforced plate
print(fab:getInventories()[1]:getStack(0).item["count"]) - expected number in stack -> got: nil
print(fab:getInventories()[1]:getStack(1).item["type"]) - expected iron rod -> got: iron rod
print(fab:getInventories()[1]:getStack(1).item["count"]) - expected number in stack -> got: nil
print(fab:getInventories()[2]:getStack(0).item["type"]) - expected frames -> got: attempt to index a nil value (field 'item')
print(fab:getInventories()[2]:getStack(0).item["count"]) 

I figured out that i can access the count directly instead of indexing a table. Hmm. Okay.
Ahh. I got the mistake. I though until a reciep is the the output inventory is available. But exactly that is wrong. Its only available with at least one item in. Is this something you can manage in your code or is this produced by the core code?
So this seams not be a bug, but it is a bit confusing cuase to count i just use count but to get the name of the item i have to use the table. 
It would be so nice if all my ideas could be solved using your very great mod. 
Just a short questions:
Would it work to bind a screen to a gpu, update the content und bind the next screen to the gpu, update the content again?
I am so sorry for wasting your time and also sorry for my english.
kind regards

**Comment by Panakotta00** [comment]
For now you can look up the result... actually... just look at the recipe configured...
No you cant bind a gpu to two screens after each other to update the screens individually... you need to use multiple ones...
Plz try to discuss stuff like such simple questions on the discord ^^
