### ISSUE TITLE
Large Screen Direction Issue

### ISSUE THREAD

**Issue by SebastianHD** [CoderDE/FicsIt-Networks#89]
When trying to place a large screen on a wall that faces exactly west (looking at the wall you would be facing east), the screen is always facing the wall instead of outwards. It is placed on the correct side of the wall but for some reason the orientation is wrong. All other wall direction (including floors and ceilings) seems to work just fine.
![LargeScreenPlacement](https://user-images.githubusercontent.com/13339699/94638922-96070f00-02a0-11eb-829c-a9378a8f7309.png)

**Comment by UKLoneWolf** [comment]
Same issue here but player is facing east screen facing west, screen does not flip on placement to face player.

![2020 10 15-20 30_01](https://user-images.githubusercontent.com/8024927/96177917-85a09680-0f26-11eb-8ce3-70250b94acf3.png)
![2020 10 15-20 30](https://user-images.githubusercontent.com/8024927/96177908-81747900-0f26-11eb-9f11-3fe6b60936b5.png)
