### ISSUE TITLE
Game crashed when attempt to get network connectors from the computer

### ISSUE THREAD

**Issue by ProgCat-op** [CoderDE/FicsIt-Networks#90]
FIN Version: 0.0.10
Description: when I try to run the following code in computer, the game crashed.
```lua
local me = component.proxy("UUID of the computer")
for k, v in pairs(me:getNetworkConnectors()) do
print(v)
end
```
[SMMDebug_2020-8-30_17-41-46.zip](https://github.com/CoderDE/FicsIt-Networks/files/5307307/SMMDebug_2020-8-30_17-41-46.zip)

**Comment by Panakotta00** [comment]
Ok, so I now know the problem, it is a more deep sitting one which should be resolved with the reflection system. So plz wait till the reflection update ^^

**Comment by Panakotta00** [comment]
This problem should be fixed in the next version
