### ISSUE TITLE
multiplayer: Large Screen no display for client but host is ok

### ISSUE THREAD

**Issue by ebarboni** [CoderDE/FicsIt-Networks#92]
Hi, we were trying with friends to compute some data over the large screen but only me (hosting) is having the visual feedback.  Client is having a full black large screen. 

If client try to run the computer he has black screen too. Both our network setup is on ultra.

Best Regards

**Comment by Panakotta00** [comment]
Which version of the mod do you have, your friend has, can you plz explain it a bit more what you did, to encounter this issue, and can you also send some screenshots as well as your code?

**Comment by ebarboni** [comment]
Mod version is 0.0.10 on both computer.

We only try to connect a large screen and display stuff. We setup a simple code to show the issue.
We add ram, a largescreen named powerscreen, gpu cpu network card (enough item to have it working on my side)

``` screen  = component.proxy(component.findComponent("powerscreen")[1])
 gpu = computer.getGPUs()[1]

 gpu:bindScreen(screen) 
 gpu:setsize(20, 20)
 gpu:setBackground(0, 0, 0, 0)
 w,h = gpu:getSize()
 gpu:fill(0,0,w,h," ")
function printToTextDisplay(text)
 print(text)
 gpu:setForeground(1, 1, 1, 1)
 gpu:setText(0, 0, text)
 gpu:setText(0, 1, text)
 gpu:setText(0, 2, text)
 gpu:setText(0, 3, text)
 gpu:setText(0, 4, text)
 end
 print(screen)
 printToTextDisplay("Test")
gpu:flush()  
 screen  = component.proxy(component.findComponent("powerscreen")[1])
 gpu = computer.getGPUs()[1]
 gpu:bindScreen(screen) 
 gpu:setsize(20, 20)
 gpu:setBackground(0, 0, 0, 0)
 w,h = gpu:getSize()
 gpu:fill(0,0,w,h," ")
function printToTextDisplay(text)
 print(text)
 gpu:setForeground(1, 1, 1, 1)
 gpu:setText(0, 0, text)
 gpu:setText(0, 1, text)
 gpu:setText(0, 2, text)
 gpu:setText(0, 3, text)
 gpu:setText(0, 4, text)
 end
 print(screen)
 printToTextDisplay("Test")
gpu:flush() 
```
on client we have black screen
![client](https://user-images.githubusercontent.com/6940099/96022784-afd45480-0e51-11eb-94ac-d12110e6dc82.jpg)

on host 5 line with test are printed
![host](https://user-images.githubusercontent.com/6940099/96022787-b06ceb00-0e51-11eb-8c96-2a07707deb6b.jpg)

Hope it helps.

**Comment by jayzosayers** [comment]
I can confirm I've had this issue too, also with 0.0.10 on both computers. I'd get screenshots but we're having another issue which I'm about to create a separate issue for. Our code is a little more complex but the results are identical.

**Comment by UKLoneWolf** [comment]
Yeah the screen is not flipping around when you place it on a wall while facing east and place the screen. Pictures below:

![2020 10 15-20 30](https://user-images.githubusercontent.com/8024927/96177479-da8fdd00-0f25-11eb-8d84-2659f66d961a.png)
![2020 10 15-20 30_01](https://user-images.githubusercontent.com/8024927/96177490-debbfa80-0f25-11eb-9d2e-ffd7f6dc51a7.png)

**Comment by sphynx1492** [comment]
I too can confirm this is happening.  Version 0.0.10.
