### ISSUE TITLE
Can't call the active Recipe

### ISSUE THREAD

**Issue by king0394** [CoderDE/FicsIt-Networks#93]
I would like to query the recipe of a constructor or assembler. When I use the getRecipe() or getRecipes() , he only writes recipe instead of the name or a table name.

**For reproduction you need:**
1x Computer
1x EEPROM
1x CPU
1x RAM
1x Network Pole

1x Construktor or Assembler

I run the following code for testing:

> x = component.proxy("3CFAE59D4360E18412B20D9212F02D1D")
> print(x:getRecipe())
> print(x:getRecipes())

**Comment by ebarboni** [comment]
You should try getRecipe().getName() 
More function on recipe over here https://docs.ficsit.app/ficsit-networks/0.0.1/lua/api/Inventory.html#_recipe

**Comment by king0394** [comment]
Thank you. 

If i write getRecipe():getName() it works.
I close the issue.
