### ISSUE TITLE
[Feature Request] IDE Development

### ISSUE THREAD

**Issue by nbrugger-tgm** [CoderDE/FicsIt-Networks#96]
If you would like to write bigger and more complex programms like me. It would be a very usefull system to be able to read a (lua) file from the real file system on your computer. This also makes it possible to write the scripts in a propper IDE.

TLDR:
* Reading Files from host system
* Providing API for autocomplete in IDE

**Comment by alyssadev** [comment]
The mod can already read files from the host system. If you add a floppy or hard drive to a computer, the contents of that drive are located at %localappdata%/FactoryGame/Saved/SaveGames/Computers. EEPROM programs are not stored in the same way; this is to introduce some difficulty and encourage using EEPROMs to store bootloaders that execute programs from floppy/hard drives.

**Comment by nbrugger-tgm** [comment]
Oh sorry seemed to have missed that. Nice design idea, is there also a lua file or library that can be used to have autocomplete or is lua designed in a way that there is no sense?
I would love too see a complex language like Java but i know the problems and headache that would come with this and i am not skilled enough to do it by myself as i am not super into C++.

But as the root of my question is answered i am closing this issue.

**Comment by alyssadev** [comment]
Regarding your second point, this is covered in the faq on the Discord server, which you're welcome to join to ask any further questions.

> **Will there be a Python/JavaScript CPU?**    
> Heck no!    
> Python/JavaScript is not designed for beeing embedded into other programs and on top of that it is fucking slow. Lua is designed specificly for that purpose to run kinda fast and beeing embedded into other programs.
